apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-for-nginx
spec:
  rules:
  - host: host.example
    http:
      paths:
      - backend:
          serviceName: service-for-nginx
          servicePort: 80
